### ISSUE TITLE
Extension Update Required

### ISSUE THREAD

**Issue by prateekkejriwal** [BranchMetrics/AdobeBranchExtension-Android#24]
Hi Team,

The Android SDK in the latest version of extension is ~8 releases behind the native one. Is there a timeline for the next update? 

[Native Android SDK](https://github.com/BranchMetrics/android-branch-deep-linking-attribution/releases/tag/5.1.0) - 5.1.0  
[Android SDK](https://github.com/BranchMetrics/android-branch-deep-linking-attribution/releases/tag/5.0.8) in the extension - 5.0.8

We have a client who is looking forward to update this extension. 

Thanks,

**Comment by nsingh-branch** [comment]
The latest update uses the Branch Android SDK v5.4.0 now.
