### ISSUE TITLE
Support for Adobe Experience Platform Mobile SDKs 2+ versions. 

### ISSUE THREAD

**Issue by philflores** [BranchMetrics/AdobeBranchExtension-Android#31]
### Describe the feature

With Mobile Core version 2.0.0 and above the AdobeBranchExtension.registerExtension method is not supported. 

https://developer.adobe.com/client-sdks/previous-versions/documentation/migrate-to-android/#update-sdk-initialization

**Comment by jf-branch** [comment]
Hey @philflores, thanks for bringing this to our attention, I've added this to our prioritized backlog and we'll begin grooming and evaluating when to take it on!

**Comment by nsingh-branch** [comment]
This has been fixed in the latest update v2.0.0.
